//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int ImageId { get; set; }
        public string ImageDescription { get; set; }
        public string ImageUrl { get; set; }
        public string ImageUrlThumb { get; set; }
        public bool IsActive { get; set; }
    }
}
